version: '3'

volumes:
  postgres-data:

networks:
  remocc-net:
    driver: bridge

services:

  web:
    build: 
      dockerfile: ./Dockerfile
      context: .
    depends_on:
      - "db"
    ports:
      - "3000:3000"
      - "2222:2222"
    restart: on-failure
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=remocc
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=remocc
      - POSTGRES_PORT=5432
      - JWT_PASSWORD=password
      - REMOCC_SSH=2222
      - REMOCC_HOST=gateways.rbccps.org
    networks: 
      - remocc-net
    volumes: 
      - ./setup/sshd/sshd_on_start.sh:/docker-entrypoint-initdb.d/init.sh
    command: bash -c "/docker-entrypoint-initdb.d/init.sh && /go/src/github.com/rraks/remocc/remocc"

  webdev:
    depends_on:
      - "db"
    ports:
      - "3000:3000"
      - "2222:2222"
    restart: on-failure
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=remocc
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=remocc
      - POSTGRES_PORT=5432
      - JWT_PASSWORD=password
      - REMOCC_SSH=2222
      - REMOCC_HOST=gateways.rbccps.org
    networks: 
      - remocc-net
    volumes: 
      - ./setup/sshd/sshd_on_start.sh:/docker-entrypoint-initdb.d/init.sh
      - ./:/remocc/
    build:
      dockerfile: Dockerfile.devel
      context: .
    command: tail -F anything
  
  db:
    image: postgres
    volumes:
      -  postgres-data:/var/lib/postgresql
      - ./setup/pg/pgsql_install.sh:/docker-entrypoint-initdb.d/init_db.sh
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=remocc
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=remocc
      - POSTGRES_PORT=5432
    expose:
      - "5432"
    networks: 
      - remocc-net


  device:
    restart: on-failure
    networks: 
      - remocc-net
    build:
      dockerfile: Dockerfile.device
      context: .
    hostname: testDevice
    volumes:
      -  ./pkg/device/:/go/src/github.com/rraks/remocc/
    command: bash -c "/usr/sbin/sshd && tail -F anything"
