version: '3'

volumes:
  postgres-data:

networks:
  remocc-net:
    driver: bridge

services:

  webdev:
    build: ./Dockerfile.devel
    depends_on:
      - "db"
    ports:
      - "3000:3000"
    restart: on-failure
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=remocc
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=remocc
      - POSTGRES_PORT=5432
    networks: 
      - remocc-net
    volumes: 
      - ./setup/sshd/sshd_on_start.sh:/docker-entrypoint-initdb.d/init.sh
      - ./:/remocc/
    build:
      dockerfile: Dockerfile.devel
      context: .
    command: tail -F anything

  
  db:
    image: postgres
    volumes:
      -  postgres-data:/var/lib/postgresql
      - ./setup/pg/pgsql_install.sh:/docker-entrypoint-initdb.d/init_db.sh
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=remocc
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=remocc
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    networks: 
      - remocc-net


