version: '3'

volumes:
  postgres-data:

networks:
  remocc-net:
    driver: bridge

services:

  web:
    build: .
    depends_on:
      - "db"
    ports:
      - "3000:3000"
    restart: on-failure
    environment:
      - POSTGRES_DB=remocc
      - POSTGRES_PASSWORD=remocc
      - POSTGRES_USER=postgres
    networks: 
      - remocc-net

  
  db:
    image: postgres
    volumes:
      -  postgres-data:/var/lib/postgresql
      - ./setup/pg/pgsql_install.sh:/docker-entrypoint-initdb.d/init_db.sh
    environment:
      - POSTGRES_DB=remocc
      - POSTGRES_PASSWORD=remocc
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    networks: 
      - remocc-net


